# app routes
-
  name: 'index'
  uriPattern: ''
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Standard'
    '@action': 'index'
    '@format': 'html'

-
  name: 'domain'
  uriPattern: 'domain'
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Standard'
    '@action': 'domain'
    '@format': 'html'

-
  name: 'domain search'
  uriPattern: 'domain/search'
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Standard'
    '@action': 'domainSearch'
    '@format': 'html'

-
  name: 'writeUrls'
  uriPattern: 'domain/write'
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Standard'
    '@action': 'domainWrite'
    '@format': 'html'

-
  name: 'Wordlist'
  uriPattern: 'wordlist'
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Standard'
    '@action': 'wordlist'
    '@format': 'html'

-
  name: 'Favorites'
  uriPattern: 'favorites'
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Standard'
    '@action': 'favorites'
    '@format': 'html'

-
  name: 'Reports'
  uriPattern: 'reports'
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Standard'
    '@action': 'reports'
    '@format': 'html'

# api routes
-
  name: 'api get port response'
  uriPattern: 'api/port'
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Api'
    '@action': 'getPortResponse'
    '@format': 'json'
  httpMethods: ['POST']

-
  name: 'api get http response'
  uriPattern: 'api/http'
  defaults:
    '@package': 'Pn3uma.App'
    '@controller': 'Api'
    '@action': 'getHttpResponse'
    '@format': 'json'
  httpMethods: ['POST']

