Pn3uma:
  App:
    network:
      port: 443
    dirsearch:
      fileToSaveUrls: '/var/www/tools.local/files/urls.tx'
Neos:
  Flow:
    mvc:
      routes:
        'Pn3uma.App': true
    http:
      applicationToken: ApplicationName
